name: Publish Packages on release

on:
  # Run when a new release is published.
  release:
    types:
      - published

jobs:
  publish:
    name: Publish Packages to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Configure and publish to NPM
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci
      - run: npm run-script build
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
